### ISSUE TITLE
Recommended papers (in the feed view) cannot be dismissed

### ISSUE THREAD

**Issue by lcharlin** [ICMLRecommender/frontend#70] opened 2017-08-04 13:40 UTC
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by LazarValkov** [comment] 2017-08-04 16:53
duplicate of #71

**Closed as completed by LazarValkov** 2017-08-04 16:53 UTC
